


all: tests


tests:
	gcc test_primitives.cc -o test_primitives.exe -I../../../src -I../.. -I../../support -lstdc++
	./test_primitives.exe
	gcc test_null.cc -o test_null.exe -I../../../src -I../.. -I../../support -lstdc++
	./test_null.exe
	gcc test_string.cc -o test_string.exe -I../../../src -I../.. -I../../support -lstdc++
	./test_string.exe
	gcc test_array.cc -o test_array.exe -I../../../src -I../.. -I../../support -lstdc++
	./test_array.exe



