version: '2.1'
services:
  postgres:
    image: postgres:12.1
    container_name: postgres
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'admin'
      - POSTGRES_DB=basyx-directory
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

