


all: test1


test1:
	gcc test_cxxhandler.cpp ../../../../src/basysid/BaSysID.cpp ../../../../src/types/BObject.cc -std=gnu++11 -o test_cxxhandler.exe -I../../../../src -I../../../.. -I../../../support -lstdc++ -Wall -g
	./test_cxxhandler.exe

