


all: tests


tests:
	gcc test_jsonprovider.cpp -W -Wall -g  ../../../../src/json/JSONTools.cpp -std=gnu++11 -o test_jsonprovider.exe -I../../../../src -I../../../.. -I../../../support -lstdc++ 
	./test_jsonprovider.exe