version: '2.1'
services:

  registry:
    image: eclipsebasyx/aas-registry:1.0.1
    container_name: dashboard-registry
    ports:
      - 4000:4000

  dashboard-aas:
    image: eclipsebasyx/dashboard-aas:0.1.0-SNAPSHOT
    container_name: dashboard-aas
    environment:
      - BaSyxDashboardSubmodel_Min=15
#      - BaSyxDashboardSubmodel_Max=30
    ports:
      - 6400:6400

  aas-wrapper:
    image: eclipsebasyx/aas-wrapper:0.1.0-SNAPSHOT
    container_name: aas-wrapper
    ports:
      - 6500:6500

  grafana:
    image: grafana/grafana:7.4.0
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./lib:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini