version: '3'
services:

  registry:
    image: eclipsebasyx/aas-registry:1.0.1
    container_name: dashboard-registry
    ports:
      - 4000:4000

  dashboard-aas:
    image: eclipsebasyx/dashboard-aas:0.1.0-SNAPSHOT
    container_name: dashboard-aas
    environment:
      - BaSyxDashboardSubmodel_Min=15
#      - BaSyxDashboardSubmodel_Max=30
    ports:
      - 6400:6400

  aas-wrapper:
    image: eclipsebasyx/aas-wrapper:0.1.0-SNAPSHOT
    container_name: aas-wrapper
    ports:
      - 6500:6500

  streamsheets:
    image: cedalo/streamsheets:1.5
    container_name: streamsheets
    ports:
      - 8081:8081
      - 8083:8083
      - 1883:1883
    volumes:
      - ./mosquitto:/etc/mosquitto-default-credentials
      - ./streamsheets:/var/lib/mongodb