


all: tests


tests: test1


test1:
	gcc test_ielement_1.cc ../../../src/types/BObject.cc  -std=gnu++11  -o test_ielement_1.exe -I../../../src -I../.. -I../../support -lstdc++
	./test_ielement_1.exe


