//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}mgmtResource"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="acmlk" type="{http://www.onem2m.org/xml/protocols}ID"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acmlk"
})
public class Acmp
    extends MgmtResource
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String acmlk;

    /**
     * Gets the value of the acmlk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcmlk() {
        return acmlk;
    }

    /**
     * Sets the value of the acmlk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcmlk(String value) {
        this.acmlk = value;
    }

}
