//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for aggregatedRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aggregatedRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="req" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="op" type="{http://www.onem2m.org/xml/protocols}operation"/&gt;
 *                   &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *                   &lt;element name="fr" type="{http://www.onem2m.org/xml/protocols}ID"/&gt;
 *                   &lt;element name="rqi" type="{http://www.onem2m.org/xml/protocols}requestID"/&gt;
 *                   &lt;element name="pc" type="{http://www.onem2m.org/xml/protocols}primitiveContent" minOccurs="0"/&gt;
 *                   &lt;element name="mi" type="{http://www.onem2m.org/xml/protocols}metaInformation" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aggregatedRequest", propOrder = {
    "req"
})
public class AggregatedRequest {

    @XmlElement(required = true)
    protected List<AggregatedRequest.Req> req;

    /**
     * Gets the value of the req property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the req property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AggregatedRequest.Req }
     * 
     * 
     */
    public List<AggregatedRequest.Req> getReq() {
        if (req == null) {
            req = new ArrayList<AggregatedRequest.Req>();
        }
        return this.req;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="op" type="{http://www.onem2m.org/xml/protocols}operation"/&gt;
     *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
     *         &lt;element name="fr" type="{http://www.onem2m.org/xml/protocols}ID"/&gt;
     *         &lt;element name="rqi" type="{http://www.onem2m.org/xml/protocols}requestID"/&gt;
     *         &lt;element name="pc" type="{http://www.onem2m.org/xml/protocols}primitiveContent" minOccurs="0"/&gt;
     *         &lt;element name="mi" type="{http://www.onem2m.org/xml/protocols}metaInformation" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "op",
        "to",
        "fr",
        "rqi",
        "pc",
        "mi"
    })
    public static class Req {

        @XmlElement(required = true)
        protected BigInteger op;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String to;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String fr;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String rqi;
        protected PrimitiveContent pc;
        protected MetaInformation mi;

        /**
         * Gets the value of the op property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getOp() {
            return op;
        }

        /**
         * Sets the value of the op property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setOp(BigInteger value) {
            this.op = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the fr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFr() {
            return fr;
        }

        /**
         * Sets the value of the fr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFr(String value) {
            this.fr = value;
        }

        /**
         * Gets the value of the rqi property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRqi() {
            return rqi;
        }

        /**
         * Sets the value of the rqi property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRqi(String value) {
            this.rqi = value;
        }

        /**
         * Gets the value of the pc property.
         * 
         * @return
         *     possible object is
         *     {@link PrimitiveContent }
         *     
         */
        public PrimitiveContent getPc() {
            return pc;
        }

        /**
         * Sets the value of the pc property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrimitiveContent }
         *     
         */
        public void setPc(PrimitiveContent value) {
            this.pc = value;
        }

        /**
         * Gets the value of the mi property.
         * 
         * @return
         *     possible object is
         *     {@link MetaInformation }
         *     
         */
        public MetaInformation getMi() {
            return mi;
        }

        /**
         * Sets the value of the mi property.
         * 
         * @param value
         *     allowed object is
         *     {@link MetaInformation }
         *     
         */
        public void setMi(MetaInformation value) {
            this.mi = value;
        }

    }

}
