//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announcedFlexContainerResource"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ajop" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ena" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/&gt;
 *           &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}smd"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}smdA"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sub"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}ajif"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}ajifa"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ajop",
    "ena",
    "ch",
    "smdOrSmdAOrSub"
})
public class Ajsoa
    extends AnnouncedFlexContainerResource
{

    @XmlElement(required = true)
    protected String ajop;
    protected Boolean ena;
    protected List<ChildResourceRef> ch;
    @XmlElements({
        @XmlElement(name = "smd", namespace = "http://www.onem2m.org/xml/protocols", type = Smd.class),
        @XmlElement(name = "smdA", namespace = "http://www.onem2m.org/xml/protocols", type = SmdA.class),
        @XmlElement(name = "sub", namespace = "http://www.onem2m.org/xml/protocols", type = Sub.class),
        @XmlElement(name = "ajif", namespace = "http://www.onem2m.org/xml/protocols", type = Ajif.class),
        @XmlElement(name = "ajifa", namespace = "http://www.onem2m.org/xml/protocols", type = Ajifa.class)
    })
    protected List<Object> smdOrSmdAOrSub;

    /**
     * Gets the value of the ajop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAjop() {
        return ajop;
    }

    /**
     * Sets the value of the ajop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAjop(String value) {
        this.ajop = value;
    }

    /**
     * Gets the value of the ena property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEna() {
        return ena;
    }

    /**
     * Sets the value of the ena property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEna(Boolean value) {
        this.ena = value;
    }

    /**
     * Gets the value of the ch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getCh() {
        if (ch == null) {
            ch = new ArrayList<ChildResourceRef>();
        }
        return this.ch;
    }

    /**
     * Gets the value of the smdOrSmdAOrSub property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smdOrSmdAOrSub property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSmdOrSmdAOrSub().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Smd }
     * {@link SmdA }
     * {@link Sub }
     * {@link Ajif }
     * {@link Ajifa }
     * 
     * 
     */
    public List<Object> getSmdOrSmdAOrSub() {
        if (smdOrSmdAOrSub == null) {
            smdOrSmdAOrSub = new ArrayList<Object>();
        }
        return this.smdOrSmdAOrSub;
    }

}
