//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}resource"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="acpi" type="{http://www.onem2m.org/xml/protocols}acpType" minOccurs="0"/&gt;
 *         &lt;element name="cst" type="{http://www.onem2m.org/xml/protocols}cseTypeID" minOccurs="0"/&gt;
 *         &lt;element name="csi" type="{http://www.onem2m.org/xml/protocols}ID"/&gt;
 *         &lt;element name="srt"&gt;
 *           &lt;simpleType&gt;
 *             &lt;list itemType="{http://www.onem2m.org/xml/protocols}resourceType" /&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="poa" type="{http://www.onem2m.org/xml/protocols}poaList"/&gt;
 *         &lt;element name="nl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *         &lt;element name="esi" type="{http://www.onem2m.org/xml/protocols}e2eSecInfo" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/&gt;
 *           &lt;choice maxOccurs="unbounded"&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}csr"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}csrA"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}nod"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}ae"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}cnt"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}grp"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}acp"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sub"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}mgc"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}lcp"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}stcg"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}stcl"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}req"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}dlv"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sch"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}mssp"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}asar"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}rol"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}tk"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sg_flexContainerResource"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acpi",
    "cst",
    "csi",
    "srt",
    "poa",
    "nl",
    "esi",
    "ch",
    "rol",
    "dlv",
    "grp",
    "sch",
    "asar",
    "ae",
    "csrA",
    "stcl",
    "cnt",
    "lcp",
    "csr",
    "stcg",
    "sub",
    "tk",
    "nod",
    "sgFlexContainerResource",
    "acp",
    "mssp",
    "req",
    "mgc"
})
public class Cb
    extends Resource
{

    @XmlList
    protected List<String> acpi;
    protected BigInteger cst;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String csi;
    @XmlList
    @XmlElement(required = true)
    protected List<BigInteger> srt;
    @XmlList
    @XmlElement(required = true)
    protected List<String> poa;
    @XmlSchemaType(name = "anyURI")
    protected String nl;
    protected E2ESecInfo esi;
    protected List<ChildResourceRef> ch;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Rol> rol;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Dlv> dlv;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Grp> grp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Sch> sch;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Asar> asar;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Ae> ae;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<CsrA> csrA;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Stcl> stcl;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Cnt> cnt;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Lcp> lcp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Csr> csr;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Stcg> stcg;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Sub> sub;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Tk> tk;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Nod> nod;
    @XmlElement(name = "sg_flexContainerResource", namespace = "http://www.onem2m.org/xml/protocols")
    protected List<FlexContainerResource> sgFlexContainerResource;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Acp> acp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Mssp> mssp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Req> req;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Mgc> mgc;

    /**
     * Gets the value of the acpi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acpi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcpi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAcpi() {
        if (acpi == null) {
            acpi = new ArrayList<String>();
        }
        return this.acpi;
    }

    /**
     * Gets the value of the cst property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCst() {
        return cst;
    }

    /**
     * Sets the value of the cst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCst(BigInteger value) {
        this.cst = value;
    }

    /**
     * Gets the value of the csi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsi() {
        return csi;
    }

    /**
     * Sets the value of the csi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsi(String value) {
        this.csi = value;
    }

    /**
     * Gets the value of the srt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the srt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSrt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getSrt() {
        if (srt == null) {
            srt = new ArrayList<BigInteger>();
        }
        return this.srt;
    }

    /**
     * Gets the value of the poa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the poa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPoa() {
        if (poa == null) {
            poa = new ArrayList<String>();
        }
        return this.poa;
    }

    /**
     * Gets the value of the nl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNl() {
        return nl;
    }

    /**
     * Sets the value of the nl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNl(String value) {
        this.nl = value;
    }

    /**
     * Gets the value of the esi property.
     * 
     * @return
     *     possible object is
     *     {@link E2ESecInfo }
     *     
     */
    public E2ESecInfo getEsi() {
        return esi;
    }

    /**
     * Sets the value of the esi property.
     * 
     * @param value
     *     allowed object is
     *     {@link E2ESecInfo }
     *     
     */
    public void setEsi(E2ESecInfo value) {
        this.esi = value;
    }

    /**
     * Gets the value of the ch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getCh() {
        if (ch == null) {
            ch = new ArrayList<ChildResourceRef>();
        }
        return this.ch;
    }

    /**
     * Gets the value of the rol property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rol property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRol().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rol }
     * 
     * 
     */
    public List<Rol> getRol() {
        if (rol == null) {
            rol = new ArrayList<Rol>();
        }
        return this.rol;
    }

    /**
     * Gets the value of the dlv property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dlv property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDlv().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dlv }
     * 
     * 
     */
    public List<Dlv> getDlv() {
        if (dlv == null) {
            dlv = new ArrayList<Dlv>();
        }
        return this.dlv;
    }

    /**
     * Gets the value of the grp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Grp }
     * 
     * 
     */
    public List<Grp> getGrp() {
        if (grp == null) {
            grp = new ArrayList<Grp>();
        }
        return this.grp;
    }

    /**
     * Gets the value of the sch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sch }
     * 
     * 
     */
    public List<Sch> getSch() {
        if (sch == null) {
            sch = new ArrayList<Sch>();
        }
        return this.sch;
    }

    /**
     * Gets the value of the asar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the asar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAsar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Asar }
     * 
     * 
     */
    public List<Asar> getAsar() {
        if (asar == null) {
            asar = new ArrayList<Asar>();
        }
        return this.asar;
    }

    /**
     * Gets the value of the ae property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ae property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ae }
     * 
     * 
     */
    public List<Ae> getAe() {
        if (ae == null) {
            ae = new ArrayList<Ae>();
        }
        return this.ae;
    }

    /**
     * Gets the value of the csrA property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the csrA property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCsrA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CsrA }
     * 
     * 
     */
    public List<CsrA> getCsrA() {
        if (csrA == null) {
            csrA = new ArrayList<CsrA>();
        }
        return this.csrA;
    }

    /**
     * Gets the value of the stcl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stcl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStcl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stcl }
     * 
     * 
     */
    public List<Stcl> getStcl() {
        if (stcl == null) {
            stcl = new ArrayList<Stcl>();
        }
        return this.stcl;
    }

    /**
     * Gets the value of the cnt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cnt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCnt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cnt }
     * 
     * 
     */
    public List<Cnt> getCnt() {
        if (cnt == null) {
            cnt = new ArrayList<Cnt>();
        }
        return this.cnt;
    }

    /**
     * Gets the value of the lcp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lcp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLcp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lcp }
     * 
     * 
     */
    public List<Lcp> getLcp() {
        if (lcp == null) {
            lcp = new ArrayList<Lcp>();
        }
        return this.lcp;
    }

    /**
     * Gets the value of the csr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the csr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCsr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Csr }
     * 
     * 
     */
    public List<Csr> getCsr() {
        if (csr == null) {
            csr = new ArrayList<Csr>();
        }
        return this.csr;
    }

    /**
     * Gets the value of the stcg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stcg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStcg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stcg }
     * 
     * 
     */
    public List<Stcg> getStcg() {
        if (stcg == null) {
            stcg = new ArrayList<Stcg>();
        }
        return this.stcg;
    }

    /**
     * Gets the value of the sub property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sub property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSub().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sub }
     * 
     * 
     */
    public List<Sub> getSub() {
        if (sub == null) {
            sub = new ArrayList<Sub>();
        }
        return this.sub;
    }

    /**
     * Gets the value of the tk property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tk property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTk().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tk }
     * 
     * 
     */
    public List<Tk> getTk() {
        if (tk == null) {
            tk = new ArrayList<Tk>();
        }
        return this.tk;
    }

    /**
     * Gets the value of the nod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nod }
     * 
     * 
     */
    public List<Nod> getNod() {
        if (nod == null) {
            nod = new ArrayList<Nod>();
        }
        return this.nod;
    }

    /**
     * Gets the value of the sgFlexContainerResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sgFlexContainerResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSgFlexContainerResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlexContainerResource }
     * 
     * 
     */
    public List<FlexContainerResource> getSgFlexContainerResource() {
        if (sgFlexContainerResource == null) {
            sgFlexContainerResource = new ArrayList<FlexContainerResource>();
        }
        return this.sgFlexContainerResource;
    }

    /**
     * Gets the value of the acp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Acp }
     * 
     * 
     */
    public List<Acp> getAcp() {
        if (acp == null) {
            acp = new ArrayList<Acp>();
        }
        return this.acp;
    }

    /**
     * Gets the value of the mssp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mssp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMssp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mssp }
     * 
     * 
     */
    public List<Mssp> getMssp() {
        if (mssp == null) {
            mssp = new ArrayList<Mssp>();
        }
        return this.mssp;
    }

    /**
     * Gets the value of the req property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the req property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Req }
     * 
     * 
     */
    public List<Req> getReq() {
        if (req == null) {
            req = new ArrayList<Req>();
        }
        return this.req;
    }

    /**
     * Gets the value of the mgc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mgc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMgc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mgc }
     * 
     * 
     */
    public List<Mgc> getMgc() {
        if (mgc == null) {
            mgc = new ArrayList<Mgc>();
        }
        return this.mgc;
    }

}
