//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announceableResource"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cst" type="{http://www.onem2m.org/xml/protocols}cseTypeID" minOccurs="0"/&gt;
 *         &lt;element name="poa" type="{http://www.onem2m.org/xml/protocols}poaList" minOccurs="0"/&gt;
 *         &lt;element name="cb" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element name="csi" type="{http://www.onem2m.org/xml/protocols}ID"/&gt;
 *         &lt;element name="mei" type="{http://www.onem2m.org/xml/protocols}externalID" minOccurs="0"/&gt;
 *         &lt;element name="tri" type="{http://www.onem2m.org/xml/protocols}triggerRecipientID" minOccurs="0"/&gt;
 *         &lt;element name="rr" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="nl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *         &lt;element name="esi" type="{http://www.onem2m.org/xml/protocols}e2eSecInfo" minOccurs="0"/&gt;
 *         &lt;element name="trn" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/&gt;
 *           &lt;choice maxOccurs="unbounded"&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}nodA"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}cnt"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}cntA"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}grp"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}grpA"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}acp"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}acpA"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sub"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}pch"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sch"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}ts"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}tsa"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}lcpA"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}aeA"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sg_flexContainerResource"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sg_announcedFlexContainerResource"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cst",
    "poa",
    "cb",
    "csi",
    "mei",
    "tri",
    "rr",
    "nl",
    "esi",
    "trn",
    "ch",
    "nodAOrCntOrCntA"
})
public class Csr
    extends AnnounceableResource
{

    protected BigInteger cst;
    @XmlList
    protected List<String> poa;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String cb;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String csi;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String mei;
    @XmlSchemaType(name = "unsignedInt")
    protected Long tri;
    protected boolean rr;
    @XmlSchemaType(name = "anyURI")
    protected String nl;
    protected E2ESecInfo esi;
    @XmlSchemaType(name = "unsignedInt")
    protected Long trn;
    protected List<ChildResourceRef> ch;
    @XmlElementRefs({
        @XmlElementRef(name = "grp", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sch", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ts", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "nodA", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cnt", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pch", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lcpA", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cntA", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sg_announcedFlexContainerResource", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "aeA", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sub", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "grpA", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sg_flexContainerResource", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tsa", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "acp", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "acpA", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> nodAOrCntOrCntA;

    /**
     * Gets the value of the cst property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCst() {
        return cst;
    }

    /**
     * Sets the value of the cst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCst(BigInteger value) {
        this.cst = value;
    }

    /**
     * Gets the value of the poa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the poa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPoa() {
        if (poa == null) {
            poa = new ArrayList<String>();
        }
        return this.poa;
    }

    /**
     * Gets the value of the cb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCb() {
        return cb;
    }

    /**
     * Sets the value of the cb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCb(String value) {
        this.cb = value;
    }

    /**
     * Gets the value of the csi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsi() {
        return csi;
    }

    /**
     * Sets the value of the csi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsi(String value) {
        this.csi = value;
    }

    /**
     * Gets the value of the mei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMei() {
        return mei;
    }

    /**
     * Sets the value of the mei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMei(String value) {
        this.mei = value;
    }

    /**
     * Gets the value of the tri property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTri() {
        return tri;
    }

    /**
     * Sets the value of the tri property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTri(Long value) {
        this.tri = value;
    }

    /**
     * Gets the value of the rr property.
     * 
     */
    public boolean isRr() {
        return rr;
    }

    /**
     * Sets the value of the rr property.
     * 
     */
    public void setRr(boolean value) {
        this.rr = value;
    }

    /**
     * Gets the value of the nl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNl() {
        return nl;
    }

    /**
     * Sets the value of the nl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNl(String value) {
        this.nl = value;
    }

    /**
     * Gets the value of the esi property.
     * 
     * @return
     *     possible object is
     *     {@link E2ESecInfo }
     *     
     */
    public E2ESecInfo getEsi() {
        return esi;
    }

    /**
     * Sets the value of the esi property.
     * 
     * @param value
     *     allowed object is
     *     {@link E2ESecInfo }
     *     
     */
    public void setEsi(E2ESecInfo value) {
        this.esi = value;
    }

    /**
     * Gets the value of the trn property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTrn() {
        return trn;
    }

    /**
     * Sets the value of the trn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTrn(Long value) {
        this.trn = value;
    }

    /**
     * Gets the value of the ch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getCh() {
        if (ch == null) {
            ch = new ArrayList<ChildResourceRef>();
        }
        return this.ch;
    }

    /**
     * Gets the value of the nodAOrCntOrCntA property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nodAOrCntOrCntA property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNodAOrCntOrCntA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Ajmc }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajif }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajsw }{@code >}
     * {@link JAXBElement }{@code <}{@link Grp }{@code >}
     * {@link JAXBElement }{@code <}{@link Sch }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajfw }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajsoa }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajswa }{@code >}
     * {@link JAXBElement }{@code <}{@link NodA }{@code >}
     * {@link JAXBElement }{@code <}{@link Pch }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajmda }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajfwa }{@code >}
     * {@link JAXBElement }{@code <}{@link AeA }{@code >}
     * {@link JAXBElement }{@code <}{@link GrpA }{@code >}
     * {@link JAXBElement }{@code <}{@link Gioa }{@code >}
     * {@link JAXBElement }{@code <}{@link Tsa }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajmd }{@code >}
     * {@link JAXBElement }{@code <}{@link Gis }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajapa }{@code >}
     * {@link JAXBElement }{@code <}{@link Ts }{@code >}
     * {@link JAXBElement }{@code <}{@link Gio }{@code >}
     * {@link JAXBElement }{@code <}{@link Cnt }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajpra }{@code >}
     * {@link JAXBElement }{@code <}{@link Gisa }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajap }{@code >}
     * {@link JAXBElement }{@code <}{@link LcpA }{@code >}
     * {@link JAXBElement }{@code <}{@link CntA }{@code >}
     * {@link JAXBElement }{@code <}{@link AnnouncedFlexContainerResource }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajifa }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajmca }{@code >}
     * {@link JAXBElement }{@code <}{@link Sub }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajpr }{@code >}
     * {@link JAXBElement }{@code <}{@link Ajso }{@code >}
     * {@link JAXBElement }{@code <}{@link FlexContainerResource }{@code >}
     * {@link JAXBElement }{@code <}{@link Acp }{@code >}
     * {@link JAXBElement }{@code <}{@link AcpA }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getNodAOrCntOrCntA() {
        if (nodAOrCntOrCntA == null) {
            nodAOrCntOrCntA = new ArrayList<JAXBElement<?>>();
        }
        return this.nodAOrCntOrCntA;
    }

}
