//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}mgmtResource"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dlb" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="man" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dty" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fwv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="swv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="hwv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}sub" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dlb",
    "man",
    "mod",
    "dty",
    "fwv",
    "swv",
    "hwv",
    "ch",
    "sub"
})
public class Dvi
    extends MgmtResource
{

    @XmlElement(required = true)
    protected String dlb;
    @XmlElement(required = true)
    protected String man;
    @XmlElement(required = true)
    protected String mod;
    @XmlElement(required = true)
    protected String dty;
    @XmlElement(required = true)
    protected String fwv;
    @XmlElement(required = true)
    protected String swv;
    @XmlElement(required = true)
    protected String hwv;
    protected List<ChildResourceRef> ch;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Sub> sub;

    /**
     * Gets the value of the dlb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlb() {
        return dlb;
    }

    /**
     * Sets the value of the dlb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlb(String value) {
        this.dlb = value;
    }

    /**
     * Gets the value of the man property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMan() {
        return man;
    }

    /**
     * Sets the value of the man property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMan(String value) {
        this.man = value;
    }

    /**
     * Gets the value of the mod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMod() {
        return mod;
    }

    /**
     * Sets the value of the mod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMod(String value) {
        this.mod = value;
    }

    /**
     * Gets the value of the dty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDty() {
        return dty;
    }

    /**
     * Sets the value of the dty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDty(String value) {
        this.dty = value;
    }

    /**
     * Gets the value of the fwv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFwv() {
        return fwv;
    }

    /**
     * Sets the value of the fwv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFwv(String value) {
        this.fwv = value;
    }

    /**
     * Gets the value of the swv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwv() {
        return swv;
    }

    /**
     * Sets the value of the swv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwv(String value) {
        this.swv = value;
    }

    /**
     * Gets the value of the hwv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHwv() {
        return hwv;
    }

    /**
     * Sets the value of the hwv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHwv(String value) {
        this.hwv = value;
    }

    /**
     * Gets the value of the ch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getCh() {
        if (ch == null) {
            ch = new ArrayList<ChildResourceRef>();
        }
        return this.ch;
    }

    /**
     * Gets the value of the sub property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sub property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSub().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sub }
     * 
     * 
     */
    public List<Sub> getSub() {
        if (sub == null) {
            sub = new ArrayList<Sub>();
        }
        return this.sub;
    }

}
