//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for dynAuthLocalTokenIdAssignments complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dynAuthLocalTokenIdAssignments"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ltia" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="lti" type="{http://www.w3.org/2001/XMLSchema}NCName"/&gt;
 *                   &lt;element name="tkid" type="{http://www.onem2m.org/xml/protocols}tokenID"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dynAuthLocalTokenIdAssignments", propOrder = {
    "ltia"
})
public class DynAuthLocalTokenIdAssignments {

    @XmlElement(required = true)
    protected List<DynAuthLocalTokenIdAssignments.Ltia> ltia;

    /**
     * Gets the value of the ltia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ltia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLtia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DynAuthLocalTokenIdAssignments.Ltia }
     * 
     * 
     */
    public List<DynAuthLocalTokenIdAssignments.Ltia> getLtia() {
        if (ltia == null) {
            ltia = new ArrayList<DynAuthLocalTokenIdAssignments.Ltia>();
        }
        return this.ltia;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="lti" type="{http://www.w3.org/2001/XMLSchema}NCName"/&gt;
     *         &lt;element name="tkid" type="{http://www.onem2m.org/xml/protocols}tokenID"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lti",
        "tkid"
    })
    public static class Ltia {

        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String lti;
        @XmlElement(required = true)
        protected String tkid;

        /**
         * Gets the value of the lti property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLti() {
            return lti;
        }

        /**
         * Sets the value of the lti property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLti(String value) {
            this.lti = value;
        }

        /**
         * Gets the value of the tkid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTkid() {
            return tkid;
        }

        /**
         * Sets the value of the tkid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTkid(String value) {
            this.tkid = value;
        }

    }

}
