//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for e2eSecInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="e2eSecInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="esf"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction&gt;
 *               &lt;simpleType&gt;
 *                 &lt;list itemType="{http://www.onem2m.org/xml/protocols}suid" /&gt;
 *               &lt;/simpleType&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="escert" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction&gt;
 *               &lt;simpleType&gt;
 *                 &lt;list itemType="{http://www.w3.org/2001/XMLSchema}base64Binary" /&gt;
 *               &lt;/simpleType&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="esro" type="{http://www.onem2m.org/xml/protocols}receiverESPrimRandObject" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "e2eSecInfo", propOrder = {
    "esf",
    "escert",
    "esro"
})
public class E2ESecInfo {

    @XmlList
    @XmlElement(required = true)
    protected List<BigInteger> esf;
    @XmlList
    protected List<byte[]> escert;
    protected ReceiverESPrimRandObject esro;

    /**
     * Gets the value of the esf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the esf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEsf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getEsf() {
        if (esf == null) {
            esf = new ArrayList<BigInteger>();
        }
        return this.esf;
    }

    /**
     * Gets the value of the escert property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the escert property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEscert().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * byte[]
     * 
     */
    public List<byte[]> getEscert() {
        if (escert == null) {
            escert = new ArrayList<byte[]>();
        }
        return this.escert;
    }

    /**
     * Gets the value of the esro property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiverESPrimRandObject }
     *     
     */
    public ReceiverESPrimRandObject getEsro() {
        return esro;
    }

    /**
     * Sets the value of the esro property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiverESPrimRandObject }
     *     
     */
    public void setEsro(ReceiverESPrimRandObject value) {
        this.esro = value;
    }

}
