//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for filterCriteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filterCriteria"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="crb" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/&gt;
 *         &lt;element name="cra" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/&gt;
 *         &lt;element name="ms" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/&gt;
 *         &lt;element name="us" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/&gt;
 *         &lt;element name="sts" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="stb" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="exb" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/&gt;
 *         &lt;element name="exa" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/&gt;
 *         &lt;element name="lbl" type="{http://www.onem2m.org/xml/protocols}labels" minOccurs="0"/&gt;
 *         &lt;element name="ty" type="{http://www.onem2m.org/xml/protocols}resourceTypeList" minOccurs="0"/&gt;
 *         &lt;element name="sza" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="szb" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="cty" type="{http://www.onem2m.org/xml/protocols}typeOfContent" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="atr" type="{http://www.onem2m.org/xml/protocols}attribute" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="fu" type="{http://www.onem2m.org/xml/protocols}filterUsage" minOccurs="0"/&gt;
 *         &lt;element name="lim" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="smf" type="{http://www.onem2m.org/xml/protocols}sparql" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="fo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="cfs" type="{http://www.onem2m.org/xml/protocols}contentFilterSyntax" minOccurs="0"/&gt;
 *         &lt;element name="cfq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lvl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="ofst" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filterCriteria", propOrder = {
    "crb",
    "cra",
    "ms",
    "us",
    "sts",
    "stb",
    "exb",
    "exa",
    "lbl",
    "ty",
    "sza",
    "szb",
    "cty",
    "atr",
    "fu",
    "lim",
    "smf",
    "fo",
    "cfs",
    "cfq",
    "lvl",
    "ofst"
})
public class FilterCriteria {

    protected String crb;
    protected String cra;
    protected String ms;
    protected String us;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger sts;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger stb;
    protected String exb;
    protected String exa;
    @XmlList
    protected List<String> lbl;
    @XmlList
    protected List<BigInteger> ty;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger sza;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger szb;
    protected List<String> cty;
    protected List<Attribute> atr;
    protected BigInteger fu;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger lim;
    protected List<String> smf;
    protected Boolean fo;
    protected BigInteger cfs;
    protected String cfq;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger lvl;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ofst;

    /**
     * Gets the value of the crb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrb() {
        return crb;
    }

    /**
     * Sets the value of the crb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrb(String value) {
        this.crb = value;
    }

    /**
     * Gets the value of the cra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCra() {
        return cra;
    }

    /**
     * Sets the value of the cra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCra(String value) {
        this.cra = value;
    }

    /**
     * Gets the value of the ms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMs() {
        return ms;
    }

    /**
     * Sets the value of the ms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMs(String value) {
        this.ms = value;
    }

    /**
     * Gets the value of the us property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUs() {
        return us;
    }

    /**
     * Sets the value of the us property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUs(String value) {
        this.us = value;
    }

    /**
     * Gets the value of the sts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSts() {
        return sts;
    }

    /**
     * Sets the value of the sts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSts(BigInteger value) {
        this.sts = value;
    }

    /**
     * Gets the value of the stb property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStb() {
        return stb;
    }

    /**
     * Sets the value of the stb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStb(BigInteger value) {
        this.stb = value;
    }

    /**
     * Gets the value of the exb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExb() {
        return exb;
    }

    /**
     * Sets the value of the exb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExb(String value) {
        this.exb = value;
    }

    /**
     * Gets the value of the exa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExa() {
        return exa;
    }

    /**
     * Sets the value of the exa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExa(String value) {
        this.exa = value;
    }

    /**
     * Gets the value of the lbl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lbl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLbl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLbl() {
        if (lbl == null) {
            lbl = new ArrayList<String>();
        }
        return this.lbl;
    }

    /**
     * Gets the value of the ty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getTy() {
        if (ty == null) {
            ty = new ArrayList<BigInteger>();
        }
        return this.ty;
    }

    /**
     * Gets the value of the sza property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSza() {
        return sza;
    }

    /**
     * Sets the value of the sza property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSza(BigInteger value) {
        this.sza = value;
    }

    /**
     * Gets the value of the szb property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSzb() {
        return szb;
    }

    /**
     * Sets the value of the szb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSzb(BigInteger value) {
        this.szb = value;
    }

    /**
     * Gets the value of the cty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCty() {
        if (cty == null) {
            cty = new ArrayList<String>();
        }
        return this.cty;
    }

    /**
     * Gets the value of the atr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the atr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAtr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attribute }
     * 
     * 
     */
    public List<Attribute> getAtr() {
        if (atr == null) {
            atr = new ArrayList<Attribute>();
        }
        return this.atr;
    }

    /**
     * Gets the value of the fu property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFu() {
        return fu;
    }

    /**
     * Sets the value of the fu property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFu(BigInteger value) {
        this.fu = value;
    }

    /**
     * Gets the value of the lim property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLim() {
        return lim;
    }

    /**
     * Sets the value of the lim property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLim(BigInteger value) {
        this.lim = value;
    }

    /**
     * Gets the value of the smf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSmf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSmf() {
        if (smf == null) {
            smf = new ArrayList<String>();
        }
        return this.smf;
    }

    /**
     * Gets the value of the fo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFo() {
        return fo;
    }

    /**
     * Sets the value of the fo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFo(Boolean value) {
        this.fo = value;
    }

    /**
     * Gets the value of the cfs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCfs() {
        return cfs;
    }

    /**
     * Sets the value of the cfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCfs(BigInteger value) {
        this.cfs = value;
    }

    /**
     * Gets the value of the cfq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfq() {
        return cfq;
    }

    /**
     * Sets the value of the cfq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfq(String value) {
        this.cfq = value;
    }

    /**
     * Gets the value of the lvl property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLvl() {
        return lvl;
    }

    /**
     * Sets the value of the lvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLvl(BigInteger value) {
        this.lvl = value;
    }

    /**
     * Gets the value of the ofst property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOfst() {
        return ofst;
    }

    /**
     * Sets the value of the ofst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOfst(BigInteger value) {
        this.ofst = value;
    }

}
