//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announcedFlexContainerResource"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="gisn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="giip" type="{http://www.onem2m.org/xml/protocols}listOfDataLinks" minOccurs="0"/&gt;
 *         &lt;element name="giop" type="{http://www.onem2m.org/xml/protocols}listOfDataLinks" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/&gt;
 *           &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}gisa"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}gioa"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}smd"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}smdA"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sub"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gisn",
    "giip",
    "giop",
    "ch",
    "gisaOrGioaOrSmd"
})
public class Gisa
    extends AnnouncedFlexContainerResource
{

    protected String gisn;
    protected ListOfDataLinks giip;
    protected ListOfDataLinks giop;
    protected List<ChildResourceRef> ch;
    @XmlElements({
        @XmlElement(name = "gisa", namespace = "http://www.onem2m.org/xml/protocols", type = Gisa.class),
        @XmlElement(name = "gioa", namespace = "http://www.onem2m.org/xml/protocols", type = Gioa.class),
        @XmlElement(name = "smd", namespace = "http://www.onem2m.org/xml/protocols", type = Smd.class),
        @XmlElement(name = "smdA", namespace = "http://www.onem2m.org/xml/protocols", type = SmdA.class),
        @XmlElement(name = "sub", namespace = "http://www.onem2m.org/xml/protocols", type = Sub.class)
    })
    protected List<Object> gisaOrGioaOrSmd;

    /**
     * Gets the value of the gisn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGisn() {
        return gisn;
    }

    /**
     * Sets the value of the gisn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGisn(String value) {
        this.gisn = value;
    }

    /**
     * Gets the value of the giip property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfDataLinks }
     *     
     */
    public ListOfDataLinks getGiip() {
        return giip;
    }

    /**
     * Sets the value of the giip property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfDataLinks }
     *     
     */
    public void setGiip(ListOfDataLinks value) {
        this.giip = value;
    }

    /**
     * Gets the value of the giop property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfDataLinks }
     *     
     */
    public ListOfDataLinks getGiop() {
        return giop;
    }

    /**
     * Sets the value of the giop property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfDataLinks }
     *     
     */
    public void setGiop(ListOfDataLinks value) {
        this.giop = value;
    }

    /**
     * Gets the value of the ch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getCh() {
        if (ch == null) {
            ch = new ArrayList<ChildResourceRef>();
        }
        return this.ch;
    }

    /**
     * Gets the value of the gisaOrGioaOrSmd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gisaOrGioaOrSmd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGisaOrGioaOrSmd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Gisa }
     * {@link Gioa }
     * {@link Smd }
     * {@link SmdA }
     * {@link Sub }
     * 
     * 
     */
    public List<Object> getGisaOrGioaOrSmd() {
        if (gisaOrGioaOrSmd == null) {
            gisaOrGioaOrSmd = new ArrayList<Object>();
        }
        return this.gisaOrGioaOrSmd;
    }

}
