//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.bosch.onem2m.xml.protocols package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SgResource_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sg_resource");
    private final static QName _SgRegularResource_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sg_regularResource");
    private final static QName _SgAnnouncedResource_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sg_announcedResource");
    private final static QName _SgAnnounceableResource_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sg_announceableResource");
    private final static QName _SgSubordinateResource_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sg_subordinateResource");
    private final static QName _SgAnnounceableSubordinateResource_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sg_announceableSubordinateResource");
    private final static QName _SgAnnouncedSubordinateResource_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sg_announcedSubordinateResource");
    private final static QName _SgMgmtResource_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sg_mgmtResource");
    private final static QName _SgAnnouncedMgmtResource_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sg_announcedMgmtResource");
    private final static QName _SgFlexContainerResource_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sg_flexContainerResource");
    private final static QName _SgAnnouncedFlexContainerResource_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sg_announcedFlexContainerResource");
    private final static QName _Sch_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sch");
    private final static QName _SchA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "schA");
    private final static QName _Ntpr_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ntpr");
    private final static QName _Sub_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sub");
    private final static QName _Acp_QNAME = new QName("http://www.onem2m.org/xml/protocols", "acp");
    private final static QName _AcpA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "acpA");
    private final static QName _Acmp_QNAME = new QName("http://www.onem2m.org/xml/protocols", "acmp");
    private final static QName _Smd_QNAME = new QName("http://www.onem2m.org/xml/protocols", "smd");
    private final static QName _SmdA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "smdA");
    private final static QName _Cin_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cin");
    private final static QName _CinA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cinA");
    private final static QName _Cnt_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cnt");
    private final static QName _CntA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cntA");
    private final static QName _Grp_QNAME = new QName("http://www.onem2m.org/xml/protocols", "grp");
    private final static QName _GrpA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "grpA");
    private final static QName _Pch_QNAME = new QName("http://www.onem2m.org/xml/protocols", "pch");
    private final static QName _Tsi_QNAME = new QName("http://www.onem2m.org/xml/protocols", "tsi");
    private final static QName _Tsia_QNAME = new QName("http://www.onem2m.org/xml/protocols", "tsia");
    private final static QName _Ts_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ts");
    private final static QName _Tsa_QNAME = new QName("http://www.onem2m.org/xml/protocols", "tsa");
    private final static QName _Trpt_QNAME = new QName("http://www.onem2m.org/xml/protocols", "trpt");
    private final static QName _TrptA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "trptA");
    private final static QName _Ae_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ae");
    private final static QName _AeA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "aeA");
    private final static QName _Ajmc_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajmc");
    private final static QName _Ajmca_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajmca");
    private final static QName _Ajmd_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajmd");
    private final static QName _Ajmda_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajmda");
    private final static QName _Ajpr_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajpr");
    private final static QName _Ajpra_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajpra");
    private final static QName _Ajif_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajif");
    private final static QName _Ajifa_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajifa");
    private final static QName _Ajso_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajso");
    private final static QName _Ajsoa_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajsoa");
    private final static QName _Ajap_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajap");
    private final static QName _Ajapa_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajapa");
    private final static QName _Andi_QNAME = new QName("http://www.onem2m.org/xml/protocols", "andi");
    private final static QName _AndiA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "andiA");
    private final static QName _Ani_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ani");
    private final static QName _AniA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "aniA");
    private final static QName _Bat_QNAME = new QName("http://www.onem2m.org/xml/protocols", "bat");
    private final static QName _BatA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "batA");
    private final static QName _Cmbf_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cmbf");
    private final static QName _Cmdf_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cmdf");
    private final static QName _Cmdv_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cmdv");
    private final static QName _Cmpv_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cmpv");
    private final static QName _Cml_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cml");
    private final static QName _Cmnr_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cmnr");
    private final static QName _Cmwr_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cmwr");
    private final static QName _Cmp_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cmp");
    private final static QName _Mem_QNAME = new QName("http://www.onem2m.org/xml/protocols", "mem");
    private final static QName _MemA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "memA");
    private final static QName _Fwr_QNAME = new QName("http://www.onem2m.org/xml/protocols", "fwr");
    private final static QName _FwrA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "fwrA");
    private final static QName _Swr_QNAME = new QName("http://www.onem2m.org/xml/protocols", "swr");
    private final static QName _SwrA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "swrA");
    private final static QName _Dvi_QNAME = new QName("http://www.onem2m.org/xml/protocols", "dvi");
    private final static QName _DviA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "dviA");
    private final static QName _Dvc_QNAME = new QName("http://www.onem2m.org/xml/protocols", "dvc");
    private final static QName _DvcA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "dvcA");
    private final static QName _Rbo_QNAME = new QName("http://www.onem2m.org/xml/protocols", "rbo");
    private final static QName _RboA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "rboA");
    private final static QName _Evl_QNAME = new QName("http://www.onem2m.org/xml/protocols", "evl");
    private final static QName _EvlA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "evlA");
    private final static QName _Nod_QNAME = new QName("http://www.onem2m.org/xml/protocols", "nod");
    private final static QName _NodA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "nodA");
    private final static QName _Lcp_QNAME = new QName("http://www.onem2m.org/xml/protocols", "lcp");
    private final static QName _LcpA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "lcpA");
    private final static QName _Csr_QNAME = new QName("http://www.onem2m.org/xml/protocols", "csr");
    private final static QName _CsrA_QNAME = new QName("http://www.onem2m.org/xml/protocols", "csrA");
    private final static QName _Exin_QNAME = new QName("http://www.onem2m.org/xml/protocols", "exin");
    private final static QName _Mgc_QNAME = new QName("http://www.onem2m.org/xml/protocols", "mgc");
    private final static QName _Evcg_QNAME = new QName("http://www.onem2m.org/xml/protocols", "evcg");
    private final static QName _Stcg_QNAME = new QName("http://www.onem2m.org/xml/protocols", "stcg");
    private final static QName _Stcl_QNAME = new QName("http://www.onem2m.org/xml/protocols", "stcl");
    private final static QName _Req_QNAME = new QName("http://www.onem2m.org/xml/protocols", "req");
    private final static QName _Dlv_QNAME = new QName("http://www.onem2m.org/xml/protocols", "dlv");
    private final static QName _Svsn_QNAME = new QName("http://www.onem2m.org/xml/protocols", "svsn");
    private final static QName _Mssp_QNAME = new QName("http://www.onem2m.org/xml/protocols", "mssp");
    private final static QName _Asar_QNAME = new QName("http://www.onem2m.org/xml/protocols", "asar");
    private final static QName _Rol_QNAME = new QName("http://www.onem2m.org/xml/protocols", "rol");
    private final static QName _Tk_QNAME = new QName("http://www.onem2m.org/xml/protocols", "tk");
    private final static QName _Cb_QNAME = new QName("http://www.onem2m.org/xml/protocols", "cb");
    private final static QName _Dac_QNAME = new QName("http://www.onem2m.org/xml/protocols", "dac");
    private final static QName _Gio_QNAME = new QName("http://www.onem2m.org/xml/protocols", "gio");
    private final static QName _Gioa_QNAME = new QName("http://www.onem2m.org/xml/protocols", "gioa");
    private final static QName _Gis_QNAME = new QName("http://www.onem2m.org/xml/protocols", "gis");
    private final static QName _Gisa_QNAME = new QName("http://www.onem2m.org/xml/protocols", "gisa");
    private final static QName _Atrl_QNAME = new QName("http://www.onem2m.org/xml/protocols", "atrl");
    private final static QName _Rce_QNAME = new QName("http://www.onem2m.org/xml/protocols", "rce");
    private final static QName _Uril_QNAME = new QName("http://www.onem2m.org/xml/protocols", "uril");
    private final static QName _Uri_QNAME = new QName("http://www.onem2m.org/xml/protocols", "uri");
    private final static QName _Agr_QNAME = new QName("http://www.onem2m.org/xml/protocols", "agr");
    private final static QName _Rrl_QNAME = new QName("http://www.onem2m.org/xml/protocols", "rrl");
    private final static QName _Dbg_QNAME = new QName("http://www.onem2m.org/xml/protocols", "dbg");
    private final static QName _Sgn_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sgn");
    private final static QName _Agn_QNAME = new QName("http://www.onem2m.org/xml/protocols", "agn");
    private final static QName _Seci_QNAME = new QName("http://www.onem2m.org/xml/protocols", "seci");
    private final static QName _Pdr_QNAME = new QName("http://www.onem2m.org/xml/protocols", "pdr");
    private final static QName _Ntp_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ntp");
    private final static QName _Ajfw_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajfw");
    private final static QName _Ajfwa_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajfwa");
    private final static QName _Ajsw_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajsw");
    private final static QName _Ajswa_QNAME = new QName("http://www.onem2m.org/xml/protocols", "ajswa");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.bosch.onem2m.xml.protocols
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DynAuthDasResponse }
     * 
     */
    public DynAuthDasResponse createDynAuthDasResponse() {
        return new DynAuthDasResponse();
    }

    /**
     * Create an instance of {@link BackOffParameters }
     * 
     */
    public BackOffParameters createBackOffParameters() {
        return new BackOffParameters();
    }

    /**
     * Create an instance of {@link DynAuthDasRequest }
     * 
     */
    public DynAuthDasRequest createDynAuthDasRequest() {
        return new DynAuthDasRequest();
    }

    /**
     * Create an instance of {@link ContentRef }
     * 
     */
    public ContentRef createContentRef() {
        return new ContentRef();
    }

    /**
     * Create an instance of {@link AccessControlRule }
     * 
     */
    public AccessControlRule createAccessControlRule() {
        return new AccessControlRule();
    }

    /**
     * Create an instance of {@link AccessControlRule.Acco }
     * 
     */
    public AccessControlRule.Acco createAccessControlRuleAcco() {
        return new AccessControlRule.Acco();
    }

    /**
     * Create an instance of {@link AggregatedRequest }
     * 
     */
    public AggregatedRequest createAggregatedRequest() {
        return new AggregatedRequest();
    }

    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link Notification.Nev }
     * 
     */
    public Notification.Nev createNotificationNev() {
        return new Notification.Nev();
    }

    /**
     * Create an instance of {@link DynAuthTokenReqInfo }
     * 
     */
    public DynAuthTokenReqInfo createDynAuthTokenReqInfo() {
        return new DynAuthTokenReqInfo();
    }

    /**
     * Create an instance of {@link DynAuthLocalTokenIdAssignments }
     * 
     */
    public DynAuthLocalTokenIdAssignments createDynAuthLocalTokenIdAssignments() {
        return new DynAuthLocalTokenIdAssignments();
    }

    /**
     * Create an instance of {@link Tk }
     * 
     */
    public Tk createTk() {
        return new Tk();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link RegularResource }
     * 
     */
    public RegularResource createRegularResource() {
        return new RegularResource();
    }

    /**
     * Create an instance of {@link AnnouncedResource }
     * 
     */
    public AnnouncedResource createAnnouncedResource() {
        return new AnnouncedResource();
    }

    /**
     * Create an instance of {@link AnnounceableResource }
     * 
     */
    public AnnounceableResource createAnnounceableResource() {
        return new AnnounceableResource();
    }

    /**
     * Create an instance of {@link SubordinateResource }
     * 
     */
    public SubordinateResource createSubordinateResource() {
        return new SubordinateResource();
    }

    /**
     * Create an instance of {@link AnnounceableSubordinateResource }
     * 
     */
    public AnnounceableSubordinateResource createAnnounceableSubordinateResource() {
        return new AnnounceableSubordinateResource();
    }

    /**
     * Create an instance of {@link AnnouncedSubordinateResource }
     * 
     */
    public AnnouncedSubordinateResource createAnnouncedSubordinateResource() {
        return new AnnouncedSubordinateResource();
    }

    /**
     * Create an instance of {@link MgmtResource }
     * 
     */
    public MgmtResource createMgmtResource() {
        return new MgmtResource();
    }

    /**
     * Create an instance of {@link AnnouncedMgmtResource }
     * 
     */
    public AnnouncedMgmtResource createAnnouncedMgmtResource() {
        return new AnnouncedMgmtResource();
    }

    /**
     * Create an instance of {@link FlexContainerResource }
     * 
     */
    public FlexContainerResource createFlexContainerResource() {
        return new FlexContainerResource();
    }

    /**
     * Create an instance of {@link AnnouncedFlexContainerResource }
     * 
     */
    public AnnouncedFlexContainerResource createAnnouncedFlexContainerResource() {
        return new AnnouncedFlexContainerResource();
    }

    /**
     * Create an instance of {@link Sch }
     * 
     */
    public Sch createSch() {
        return new Sch();
    }

    /**
     * Create an instance of {@link SchA }
     * 
     */
    public SchA createSchA() {
        return new SchA();
    }

    /**
     * Create an instance of {@link Ntpr }
     * 
     */
    public Ntpr createNtpr() {
        return new Ntpr();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link Acp }
     * 
     */
    public Acp createAcp() {
        return new Acp();
    }

    /**
     * Create an instance of {@link AcpA }
     * 
     */
    public AcpA createAcpA() {
        return new AcpA();
    }

    /**
     * Create an instance of {@link Acmp }
     * 
     */
    public Acmp createAcmp() {
        return new Acmp();
    }

    /**
     * Create an instance of {@link Smd }
     * 
     */
    public Smd createSmd() {
        return new Smd();
    }

    /**
     * Create an instance of {@link SmdA }
     * 
     */
    public SmdA createSmdA() {
        return new SmdA();
    }

    /**
     * Create an instance of {@link Cin }
     * 
     */
    public Cin createCin() {
        return new Cin();
    }

    /**
     * Create an instance of {@link CinA }
     * 
     */
    public CinA createCinA() {
        return new CinA();
    }

    /**
     * Create an instance of {@link Cnt }
     * 
     */
    public Cnt createCnt() {
        return new Cnt();
    }

    /**
     * Create an instance of {@link CntA }
     * 
     */
    public CntA createCntA() {
        return new CntA();
    }

    /**
     * Create an instance of {@link Grp }
     * 
     */
    public Grp createGrp() {
        return new Grp();
    }

    /**
     * Create an instance of {@link GrpA }
     * 
     */
    public GrpA createGrpA() {
        return new GrpA();
    }

    /**
     * Create an instance of {@link Pch }
     * 
     */
    public Pch createPch() {
        return new Pch();
    }

    /**
     * Create an instance of {@link Tsi }
     * 
     */
    public Tsi createTsi() {
        return new Tsi();
    }

    /**
     * Create an instance of {@link Tsia }
     * 
     */
    public Tsia createTsia() {
        return new Tsia();
    }

    /**
     * Create an instance of {@link Ts }
     * 
     */
    public Ts createTs() {
        return new Ts();
    }

    /**
     * Create an instance of {@link Tsa }
     * 
     */
    public Tsa createTsa() {
        return new Tsa();
    }

    /**
     * Create an instance of {@link Trpt }
     * 
     */
    public Trpt createTrpt() {
        return new Trpt();
    }

    /**
     * Create an instance of {@link TrptA }
     * 
     */
    public TrptA createTrptA() {
        return new TrptA();
    }

    /**
     * Create an instance of {@link Ae }
     * 
     */
    public Ae createAe() {
        return new Ae();
    }

    /**
     * Create an instance of {@link AeA }
     * 
     */
    public AeA createAeA() {
        return new AeA();
    }

    /**
     * Create an instance of {@link Ajmc }
     * 
     */
    public Ajmc createAjmc() {
        return new Ajmc();
    }

    /**
     * Create an instance of {@link Ajmca }
     * 
     */
    public Ajmca createAjmca() {
        return new Ajmca();
    }

    /**
     * Create an instance of {@link Ajmd }
     * 
     */
    public Ajmd createAjmd() {
        return new Ajmd();
    }

    /**
     * Create an instance of {@link Ajmda }
     * 
     */
    public Ajmda createAjmda() {
        return new Ajmda();
    }

    /**
     * Create an instance of {@link Ajpr }
     * 
     */
    public Ajpr createAjpr() {
        return new Ajpr();
    }

    /**
     * Create an instance of {@link Ajpra }
     * 
     */
    public Ajpra createAjpra() {
        return new Ajpra();
    }

    /**
     * Create an instance of {@link Ajif }
     * 
     */
    public Ajif createAjif() {
        return new Ajif();
    }

    /**
     * Create an instance of {@link Ajifa }
     * 
     */
    public Ajifa createAjifa() {
        return new Ajifa();
    }

    /**
     * Create an instance of {@link Ajso }
     * 
     */
    public Ajso createAjso() {
        return new Ajso();
    }

    /**
     * Create an instance of {@link Ajsoa }
     * 
     */
    public Ajsoa createAjsoa() {
        return new Ajsoa();
    }

    /**
     * Create an instance of {@link Ajap }
     * 
     */
    public Ajap createAjap() {
        return new Ajap();
    }

    /**
     * Create an instance of {@link Ajapa }
     * 
     */
    public Ajapa createAjapa() {
        return new Ajapa();
    }

    /**
     * Create an instance of {@link Andi }
     * 
     */
    public Andi createAndi() {
        return new Andi();
    }

    /**
     * Create an instance of {@link AndiA }
     * 
     */
    public AndiA createAndiA() {
        return new AndiA();
    }

    /**
     * Create an instance of {@link Ani }
     * 
     */
    public Ani createAni() {
        return new Ani();
    }

    /**
     * Create an instance of {@link AniA }
     * 
     */
    public AniA createAniA() {
        return new AniA();
    }

    /**
     * Create an instance of {@link Bat }
     * 
     */
    public Bat createBat() {
        return new Bat();
    }

    /**
     * Create an instance of {@link BatA }
     * 
     */
    public BatA createBatA() {
        return new BatA();
    }

    /**
     * Create an instance of {@link Cmbf }
     * 
     */
    public Cmbf createCmbf() {
        return new Cmbf();
    }

    /**
     * Create an instance of {@link Cmdf }
     * 
     */
    public Cmdf createCmdf() {
        return new Cmdf();
    }

    /**
     * Create an instance of {@link Cmdv }
     * 
     */
    public Cmdv createCmdv() {
        return new Cmdv();
    }

    /**
     * Create an instance of {@link Cmpv }
     * 
     */
    public Cmpv createCmpv() {
        return new Cmpv();
    }

    /**
     * Create an instance of {@link Cml }
     * 
     */
    public Cml createCml() {
        return new Cml();
    }

    /**
     * Create an instance of {@link Cmnr }
     * 
     */
    public Cmnr createCmnr() {
        return new Cmnr();
    }

    /**
     * Create an instance of {@link Cmwr }
     * 
     */
    public Cmwr createCmwr() {
        return new Cmwr();
    }

    /**
     * Create an instance of {@link Cmp }
     * 
     */
    public Cmp createCmp() {
        return new Cmp();
    }

    /**
     * Create an instance of {@link Mem }
     * 
     */
    public Mem createMem() {
        return new Mem();
    }

    /**
     * Create an instance of {@link MemA }
     * 
     */
    public MemA createMemA() {
        return new MemA();
    }

    /**
     * Create an instance of {@link Fwr }
     * 
     */
    public Fwr createFwr() {
        return new Fwr();
    }

    /**
     * Create an instance of {@link FwrA }
     * 
     */
    public FwrA createFwrA() {
        return new FwrA();
    }

    /**
     * Create an instance of {@link Swr }
     * 
     */
    public Swr createSwr() {
        return new Swr();
    }

    /**
     * Create an instance of {@link SwrA }
     * 
     */
    public SwrA createSwrA() {
        return new SwrA();
    }

    /**
     * Create an instance of {@link Dvi }
     * 
     */
    public Dvi createDvi() {
        return new Dvi();
    }

    /**
     * Create an instance of {@link DviA }
     * 
     */
    public DviA createDviA() {
        return new DviA();
    }

    /**
     * Create an instance of {@link Dvc }
     * 
     */
    public Dvc createDvc() {
        return new Dvc();
    }

    /**
     * Create an instance of {@link DvcA }
     * 
     */
    public DvcA createDvcA() {
        return new DvcA();
    }

    /**
     * Create an instance of {@link Rbo }
     * 
     */
    public Rbo createRbo() {
        return new Rbo();
    }

    /**
     * Create an instance of {@link RboA }
     * 
     */
    public RboA createRboA() {
        return new RboA();
    }

    /**
     * Create an instance of {@link Evl }
     * 
     */
    public Evl createEvl() {
        return new Evl();
    }

    /**
     * Create an instance of {@link EvlA }
     * 
     */
    public EvlA createEvlA() {
        return new EvlA();
    }

    /**
     * Create an instance of {@link Nod }
     * 
     */
    public Nod createNod() {
        return new Nod();
    }

    /**
     * Create an instance of {@link NodA }
     * 
     */
    public NodA createNodA() {
        return new NodA();
    }

    /**
     * Create an instance of {@link Lcp }
     * 
     */
    public Lcp createLcp() {
        return new Lcp();
    }

    /**
     * Create an instance of {@link LcpA }
     * 
     */
    public LcpA createLcpA() {
        return new LcpA();
    }

    /**
     * Create an instance of {@link Csr }
     * 
     */
    public Csr createCsr() {
        return new Csr();
    }

    /**
     * Create an instance of {@link CsrA }
     * 
     */
    public CsrA createCsrA() {
        return new CsrA();
    }

    /**
     * Create an instance of {@link Exin }
     * 
     */
    public Exin createExin() {
        return new Exin();
    }

    /**
     * Create an instance of {@link Mgc }
     * 
     */
    public Mgc createMgc() {
        return new Mgc();
    }

    /**
     * Create an instance of {@link Evcg }
     * 
     */
    public Evcg createEvcg() {
        return new Evcg();
    }

    /**
     * Create an instance of {@link Stcg }
     * 
     */
    public Stcg createStcg() {
        return new Stcg();
    }

    /**
     * Create an instance of {@link Stcl }
     * 
     */
    public Stcl createStcl() {
        return new Stcl();
    }

    /**
     * Create an instance of {@link org.eclipse.basyx.onem2m.xml.protocols.Req }
     * 
     */
    public org.eclipse.basyx.onem2m.xml.protocols.Req createReq() {
        return new org.eclipse.basyx.onem2m.xml.protocols.Req();
    }

    /**
     * Create an instance of {@link Dlv }
     * 
     */
    public Dlv createDlv() {
        return new Dlv();
    }

    /**
     * Create an instance of {@link Svsn }
     * 
     */
    public Svsn createSvsn() {
        return new Svsn();
    }

    /**
     * Create an instance of {@link Mssp }
     * 
     */
    public Mssp createMssp() {
        return new Mssp();
    }

    /**
     * Create an instance of {@link Asar }
     * 
     */
    public Asar createAsar() {
        return new Asar();
    }

    /**
     * Create an instance of {@link Rol }
     * 
     */
    public Rol createRol() {
        return new Rol();
    }

    /**
     * Create an instance of {@link Cb }
     * 
     */
    public Cb createCb() {
        return new Cb();
    }

    /**
     * Create an instance of {@link Dac }
     * 
     */
    public Dac createDac() {
        return new Dac();
    }

    /**
     * Create an instance of {@link Gio }
     * 
     */
    public Gio createGio() {
        return new Gio();
    }

    /**
     * Create an instance of {@link Gioa }
     * 
     */
    public Gioa createGioa() {
        return new Gioa();
    }

    /**
     * Create an instance of {@link Gis }
     * 
     */
    public Gis createGis() {
        return new Gis();
    }

    /**
     * Create an instance of {@link Gisa }
     * 
     */
    public Gisa createGisa() {
        return new Gisa();
    }

    /**
     * Create an instance of {@link Rqp }
     * 
     */
    public Rqp createRqp() {
        return new Rqp();
    }

    /**
     * Create an instance of {@link PrimitiveContent }
     * 
     */
    public PrimitiveContent createPrimitiveContent() {
        return new PrimitiveContent();
    }

    /**
     * Create an instance of {@link ResponseTypeInfo }
     * 
     */
    public ResponseTypeInfo createResponseTypeInfo() {
        return new ResponseTypeInfo();
    }

    /**
     * Create an instance of {@link FilterCriteria }
     * 
     */
    public FilterCriteria createFilterCriteria() {
        return new FilterCriteria();
    }

    /**
     * Create an instance of {@link Rsp }
     * 
     */
    public Rsp createRsp() {
        return new Rsp();
    }

    /**
     * Create an instance of {@link ResourceWrapper }
     * 
     */
    public ResourceWrapper createResourceWrapper() {
        return new ResourceWrapper();
    }

    /**
     * Create an instance of {@link AggregatedResponse }
     * 
     */
    public AggregatedResponse createAggregatedResponse() {
        return new AggregatedResponse();
    }

    /**
     * Create an instance of {@link ListOfChildResourceRef }
     * 
     */
    public ListOfChildResourceRef createListOfChildResourceRef() {
        return new ListOfChildResourceRef();
    }

    /**
     * Create an instance of {@link AggregatedNotification }
     * 
     */
    public AggregatedNotification createAggregatedNotification() {
        return new AggregatedNotification();
    }

    /**
     * Create an instance of {@link SecurityInfo }
     * 
     */
    public SecurityInfo createSecurityInfo() {
        return new SecurityInfo();
    }

    /**
     * Create an instance of {@link Pdr }
     * 
     */
    public Pdr createPdr() {
        return new Pdr();
    }

    /**
     * Create an instance of {@link Ntp }
     * 
     */
    public Ntp createNtp() {
        return new Ntp();
    }

    /**
     * Create an instance of {@link Ajfw }
     * 
     */
    public Ajfw createAjfw() {
        return new Ajfw();
    }

    /**
     * Create an instance of {@link Ajfwa }
     * 
     */
    public Ajfwa createAjfwa() {
        return new Ajfwa();
    }

    /**
     * Create an instance of {@link Ajsw }
     * 
     */
    public Ajsw createAjsw() {
        return new Ajsw();
    }

    /**
     * Create an instance of {@link Ajswa }
     * 
     */
    public Ajswa createAjswa() {
        return new Ajswa();
    }

    /**
     * Create an instance of {@link DeliveryMetaData }
     * 
     */
    public DeliveryMetaData createDeliveryMetaData() {
        return new DeliveryMetaData();
    }

    /**
     * Create an instance of {@link MetaInformation }
     * 
     */
    public MetaInformation createMetaInformation() {
        return new MetaInformation();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link ScheduleEntries }
     * 
     */
    public ScheduleEntries createScheduleEntries() {
        return new ScheduleEntries();
    }

    /**
     * Create an instance of {@link ActionStatus }
     * 
     */
    public ActionStatus createActionStatus() {
        return new ActionStatus();
    }

    /**
     * Create an instance of {@link AnyArgType }
     * 
     */
    public AnyArgType createAnyArgType() {
        return new AnyArgType();
    }

    /**
     * Create an instance of {@link ResetArgsType }
     * 
     */
    public ResetArgsType createResetArgsType() {
        return new ResetArgsType();
    }

    /**
     * Create an instance of {@link RebootArgsType }
     * 
     */
    public RebootArgsType createRebootArgsType() {
        return new RebootArgsType();
    }

    /**
     * Create an instance of {@link UploadArgsType }
     * 
     */
    public UploadArgsType createUploadArgsType() {
        return new UploadArgsType();
    }

    /**
     * Create an instance of {@link DownloadArgsType }
     * 
     */
    public DownloadArgsType createDownloadArgsType() {
        return new DownloadArgsType();
    }

    /**
     * Create an instance of {@link SoftwareInstallArgsType }
     * 
     */
    public SoftwareInstallArgsType createSoftwareInstallArgsType() {
        return new SoftwareInstallArgsType();
    }

    /**
     * Create an instance of {@link SoftwareUpdateArgsType }
     * 
     */
    public SoftwareUpdateArgsType createSoftwareUpdateArgsType() {
        return new SoftwareUpdateArgsType();
    }

    /**
     * Create an instance of {@link SoftwareUninstallArgsType }
     * 
     */
    public SoftwareUninstallArgsType createSoftwareUninstallArgsType() {
        return new SoftwareUninstallArgsType();
    }

    /**
     * Create an instance of {@link ExecReqArgsListType }
     * 
     */
    public ExecReqArgsListType createExecReqArgsListType() {
        return new ExecReqArgsListType();
    }

    /**
     * Create an instance of {@link MgmtLinkRef }
     * 
     */
    public MgmtLinkRef createMgmtLinkRef() {
        return new MgmtLinkRef();
    }

    /**
     * Create an instance of {@link SetOfAcrs }
     * 
     */
    public SetOfAcrs createSetOfAcrs() {
        return new SetOfAcrs();
    }

    /**
     * Create an instance of {@link ChildResourceRef }
     * 
     */
    public ChildResourceRef createChildResourceRef() {
        return new ChildResourceRef();
    }

    /**
     * Create an instance of {@link OperationResult }
     * 
     */
    public OperationResult createOperationResult() {
        return new OperationResult();
    }

    /**
     * Create an instance of {@link DeletionContexts }
     * 
     */
    public DeletionContexts createDeletionContexts() {
        return new DeletionContexts();
    }

    /**
     * Create an instance of {@link LocationRegion }
     * 
     */
    public LocationRegion createLocationRegion() {
        return new LocationRegion();
    }

    /**
     * Create an instance of {@link MissingData }
     * 
     */
    public MissingData createMissingData() {
        return new MissingData();
    }

    /**
     * Create an instance of {@link ReceiverESPrimRandObject }
     * 
     */
    public ReceiverESPrimRandObject createReceiverESPrimRandObject() {
        return new ReceiverESPrimRandObject();
    }

    /**
     * Create an instance of {@link OriginatorESPrimRandObject }
     * 
     */
    public OriginatorESPrimRandObject createOriginatorESPrimRandObject() {
        return new OriginatorESPrimRandObject();
    }

    /**
     * Create an instance of {@link E2ESecInfo }
     * 
     */
    public E2ESecInfo createE2ESecInfo() {
        return new E2ESecInfo();
    }

    /**
     * Create an instance of {@link TokenPermission }
     * 
     */
    public TokenPermission createTokenPermission() {
        return new TokenPermission();
    }

    /**
     * Create an instance of {@link TokenPermissions }
     * 
     */
    public TokenPermissions createTokenPermissions() {
        return new TokenPermissions();
    }

    /**
     * Create an instance of {@link TokenClaimSet }
     * 
     */
    public TokenClaimSet createTokenClaimSet() {
        return new TokenClaimSet();
    }

    /**
     * Create an instance of {@link DynAuthTokenSummary }
     * 
     */
    public DynAuthTokenSummary createDynAuthTokenSummary() {
        return new DynAuthTokenSummary();
    }

    /**
     * Create an instance of {@link ListOfDataLinks }
     * 
     */
    public ListOfDataLinks createListOfDataLinks() {
        return new ListOfDataLinks();
    }

    /**
     * Create an instance of {@link DataLink }
     * 
     */
    public DataLink createDataLink() {
        return new DataLink();
    }

    /**
     * Create an instance of {@link EventNotificationCriteria }
     * 
     */
    public EventNotificationCriteria createEventNotificationCriteria() {
        return new EventNotificationCriteria();
    }

    /**
     * Create an instance of {@link BatchNotify }
     * 
     */
    public BatchNotify createBatchNotify() {
        return new BatchNotify();
    }

    /**
     * Create an instance of {@link RateLimit }
     * 
     */
    public RateLimit createRateLimit() {
        return new RateLimit();
    }

    /**
     * Create an instance of {@link DynAuthDasResponse.Dai }
     * 
     */
    public DynAuthDasResponse.Dai createDynAuthDasResponseDai() {
        return new DynAuthDasResponse.Dai();
    }

    /**
     * Create an instance of {@link BackOffParameters.Bops }
     * 
     */
    public BackOffParameters.Bops createBackOffParametersBops() {
        return new BackOffParameters.Bops();
    }

    /**
     * Create an instance of {@link DynAuthDasRequest.Oip }
     * 
     */
    public DynAuthDasRequest.Oip createDynAuthDasRequestOip() {
        return new DynAuthDasRequest.Oip();
    }

    /**
     * Create an instance of {@link ContentRef.Urir }
     * 
     */
    public ContentRef.Urir createContentRefUrir() {
        return new ContentRef.Urir();
    }

    /**
     * Create an instance of {@link AccessControlRule.Acco.Acip }
     * 
     */
    public AccessControlRule.Acco.Acip createAccessControlRuleAccoAcip() {
        return new AccessControlRule.Acco.Acip();
    }

    /**
     * Create an instance of {@link AggregatedRequest.Req }
     * 
     */
    public AggregatedRequest.Req createAggregatedRequestReq() {
        return new AggregatedRequest.Req();
    }

    /**
     * Create an instance of {@link Notification.Idr }
     * 
     */
    public Notification.Idr createNotificationIdr() {
        return new Notification.Idr();
    }

    /**
     * Create an instance of {@link Notification.Nev.Om }
     * 
     */
    public Notification.Nev.Om createNotificationNevOm() {
        return new Notification.Nev.Om();
    }

    /**
     * Create an instance of {@link DynAuthTokenReqInfo.Dasi }
     * 
     */
    public DynAuthTokenReqInfo.Dasi createDynAuthTokenReqInfoDasi() {
        return new DynAuthTokenReqInfo.Dasi();
    }

    /**
     * Create an instance of {@link DynAuthLocalTokenIdAssignments.Ltia }
     * 
     */
    public DynAuthLocalTokenIdAssignments.Ltia createDynAuthLocalTokenIdAssignmentsLtia() {
        return new DynAuthLocalTokenIdAssignments.Ltia();
    }

    /**
     * Create an instance of {@link Tk.Tkps }
     * 
     */
    public Tk.Tkps createTkTkps() {
        return new Tk.Tkps();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sg_resource")
    public JAXBElement<Resource> createSgResource(Resource value) {
        return new JAXBElement<Resource>(_SgResource_QNAME, Resource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegularResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sg_regularResource")
    public JAXBElement<RegularResource> createSgRegularResource(RegularResource value) {
        return new JAXBElement<RegularResource>(_SgRegularResource_QNAME, RegularResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnouncedResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sg_announcedResource")
    public JAXBElement<AnnouncedResource> createSgAnnouncedResource(AnnouncedResource value) {
        return new JAXBElement<AnnouncedResource>(_SgAnnouncedResource_QNAME, AnnouncedResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnounceableResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sg_announceableResource")
    public JAXBElement<AnnounceableResource> createSgAnnounceableResource(AnnounceableResource value) {
        return new JAXBElement<AnnounceableResource>(_SgAnnounceableResource_QNAME, AnnounceableResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubordinateResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sg_subordinateResource")
    public JAXBElement<SubordinateResource> createSgSubordinateResource(SubordinateResource value) {
        return new JAXBElement<SubordinateResource>(_SgSubordinateResource_QNAME, SubordinateResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnounceableSubordinateResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sg_announceableSubordinateResource")
    public JAXBElement<AnnounceableSubordinateResource> createSgAnnounceableSubordinateResource(AnnounceableSubordinateResource value) {
        return new JAXBElement<AnnounceableSubordinateResource>(_SgAnnounceableSubordinateResource_QNAME, AnnounceableSubordinateResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnouncedSubordinateResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sg_announcedSubordinateResource")
    public JAXBElement<AnnouncedSubordinateResource> createSgAnnouncedSubordinateResource(AnnouncedSubordinateResource value) {
        return new JAXBElement<AnnouncedSubordinateResource>(_SgAnnouncedSubordinateResource_QNAME, AnnouncedSubordinateResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgmtResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sg_mgmtResource")
    public JAXBElement<MgmtResource> createSgMgmtResource(MgmtResource value) {
        return new JAXBElement<MgmtResource>(_SgMgmtResource_QNAME, MgmtResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnouncedMgmtResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sg_announcedMgmtResource")
    public JAXBElement<AnnouncedMgmtResource> createSgAnnouncedMgmtResource(AnnouncedMgmtResource value) {
        return new JAXBElement<AnnouncedMgmtResource>(_SgAnnouncedMgmtResource_QNAME, AnnouncedMgmtResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlexContainerResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sg_flexContainerResource")
    public JAXBElement<FlexContainerResource> createSgFlexContainerResource(FlexContainerResource value) {
        return new JAXBElement<FlexContainerResource>(_SgFlexContainerResource_QNAME, FlexContainerResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnouncedFlexContainerResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sg_announcedFlexContainerResource")
    public JAXBElement<AnnouncedFlexContainerResource> createSgAnnouncedFlexContainerResource(AnnouncedFlexContainerResource value) {
        return new JAXBElement<AnnouncedFlexContainerResource>(_SgAnnouncedFlexContainerResource_QNAME, AnnouncedFlexContainerResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sch", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableSubordinateResource")
    public JAXBElement<Sch> createSch(Sch value) {
        return new JAXBElement<Sch>(_Sch_QNAME, Sch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "schA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedSubordinateResource")
    public JAXBElement<SchA> createSchA(SchA value) {
        return new JAXBElement<SchA>(_SchA_QNAME, SchA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ntpr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ntpr", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Ntpr> createNtpr(Ntpr value) {
        return new JAXBElement<Ntpr>(_Ntpr_QNAME, Ntpr.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sub }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sub", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Sub> createSub(Sub value) {
        return new JAXBElement<Sub>(_Sub_QNAME, Sub.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Acp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "acp", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableSubordinateResource")
    public JAXBElement<Acp> createAcp(Acp value) {
        return new JAXBElement<Acp>(_Acp_QNAME, Acp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcpA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "acpA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedSubordinateResource")
    public JAXBElement<AcpA> createAcpA(AcpA value) {
        return new JAXBElement<AcpA>(_AcpA_QNAME, AcpA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Acmp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "acmp", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Acmp> createAcmp(Acmp value) {
        return new JAXBElement<Acmp>(_Acmp_QNAME, Acmp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Smd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "smd", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableResource")
    public JAXBElement<Smd> createSmd(Smd value) {
        return new JAXBElement<Smd>(_Smd_QNAME, Smd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SmdA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "smdA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedResource")
    public JAXBElement<SmdA> createSmdA(SmdA value) {
        return new JAXBElement<SmdA>(_SmdA_QNAME, SmdA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cin", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableSubordinateResource")
    public JAXBElement<Cin> createCin(Cin value) {
        return new JAXBElement<Cin>(_Cin_QNAME, Cin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CinA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cinA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedSubordinateResource")
    public JAXBElement<CinA> createCinA(CinA value) {
        return new JAXBElement<CinA>(_CinA_QNAME, CinA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cnt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cnt", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableResource")
    public JAXBElement<Cnt> createCnt(Cnt value) {
        return new JAXBElement<Cnt>(_Cnt_QNAME, Cnt.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CntA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cntA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedResource")
    public JAXBElement<CntA> createCntA(CntA value) {
        return new JAXBElement<CntA>(_CntA_QNAME, CntA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Grp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "grp", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableResource")
    public JAXBElement<Grp> createGrp(Grp value) {
        return new JAXBElement<Grp>(_Grp_QNAME, Grp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GrpA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "grpA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedResource")
    public JAXBElement<GrpA> createGrpA(GrpA value) {
        return new JAXBElement<GrpA>(_GrpA_QNAME, GrpA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "pch", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_subordinateResource")
    public JAXBElement<Pch> createPch(Pch value) {
        return new JAXBElement<Pch>(_Pch_QNAME, Pch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tsi }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "tsi", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableSubordinateResource")
    public JAXBElement<Tsi> createTsi(Tsi value) {
        return new JAXBElement<Tsi>(_Tsi_QNAME, Tsi.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tsia }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "tsia", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedSubordinateResource")
    public JAXBElement<Tsia> createTsia(Tsia value) {
        return new JAXBElement<Tsia>(_Tsia_QNAME, Tsia.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ts", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableResource")
    public JAXBElement<Ts> createTs(Ts value) {
        return new JAXBElement<Ts>(_Ts_QNAME, Ts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tsa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "tsa", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedResource")
    public JAXBElement<Tsa> createTsa(Tsa value) {
        return new JAXBElement<Tsa>(_Tsa_QNAME, Tsa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Trpt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "trpt", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableResource")
    public JAXBElement<Trpt> createTrpt(Trpt value) {
        return new JAXBElement<Trpt>(_Trpt_QNAME, Trpt.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrptA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "trptA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedResource")
    public JAXBElement<TrptA> createTrptA(TrptA value) {
        return new JAXBElement<TrptA>(_TrptA_QNAME, TrptA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ae }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ae", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableResource")
    public JAXBElement<Ae> createAe(Ae value) {
        return new JAXBElement<Ae>(_Ae_QNAME, Ae.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AeA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "aeA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedResource")
    public JAXBElement<AeA> createAeA(AeA value) {
        return new JAXBElement<AeA>(_AeA_QNAME, AeA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajmc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajmc", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_flexContainerResource")
    public JAXBElement<Ajmc> createAjmc(Ajmc value) {
        return new JAXBElement<Ajmc>(_Ajmc_QNAME, Ajmc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajmca }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajmca", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedFlexContainerResource")
    public JAXBElement<Ajmca> createAjmca(Ajmca value) {
        return new JAXBElement<Ajmca>(_Ajmca_QNAME, Ajmca.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajmd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajmd", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_flexContainerResource")
    public JAXBElement<Ajmd> createAjmd(Ajmd value) {
        return new JAXBElement<Ajmd>(_Ajmd_QNAME, Ajmd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajmda }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajmda", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedFlexContainerResource")
    public JAXBElement<Ajmda> createAjmda(Ajmda value) {
        return new JAXBElement<Ajmda>(_Ajmda_QNAME, Ajmda.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajpr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajpr", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_flexContainerResource")
    public JAXBElement<Ajpr> createAjpr(Ajpr value) {
        return new JAXBElement<Ajpr>(_Ajpr_QNAME, Ajpr.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajpra }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajpra", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedFlexContainerResource")
    public JAXBElement<Ajpra> createAjpra(Ajpra value) {
        return new JAXBElement<Ajpra>(_Ajpra_QNAME, Ajpra.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajif }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajif", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_flexContainerResource")
    public JAXBElement<Ajif> createAjif(Ajif value) {
        return new JAXBElement<Ajif>(_Ajif_QNAME, Ajif.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajifa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajifa", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedFlexContainerResource")
    public JAXBElement<Ajifa> createAjifa(Ajifa value) {
        return new JAXBElement<Ajifa>(_Ajifa_QNAME, Ajifa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajso }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajso", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_flexContainerResource")
    public JAXBElement<Ajso> createAjso(Ajso value) {
        return new JAXBElement<Ajso>(_Ajso_QNAME, Ajso.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajsoa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajsoa", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedFlexContainerResource")
    public JAXBElement<Ajsoa> createAjsoa(Ajsoa value) {
        return new JAXBElement<Ajsoa>(_Ajsoa_QNAME, Ajsoa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajap }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajap", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_flexContainerResource")
    public JAXBElement<Ajap> createAjap(Ajap value) {
        return new JAXBElement<Ajap>(_Ajap_QNAME, Ajap.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajapa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajapa", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedFlexContainerResource")
    public JAXBElement<Ajapa> createAjapa(Ajapa value) {
        return new JAXBElement<Ajapa>(_Ajapa_QNAME, Ajapa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Andi }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "andi", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Andi> createAndi(Andi value) {
        return new JAXBElement<Andi>(_Andi_QNAME, Andi.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AndiA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "andiA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedMgmtResource")
    public JAXBElement<AndiA> createAndiA(AndiA value) {
        return new JAXBElement<AndiA>(_AndiA_QNAME, AndiA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ani }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ani", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Ani> createAni(Ani value) {
        return new JAXBElement<Ani>(_Ani_QNAME, Ani.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AniA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "aniA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedMgmtResource")
    public JAXBElement<AniA> createAniA(AniA value) {
        return new JAXBElement<AniA>(_AniA_QNAME, AniA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Bat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "bat", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Bat> createBat(Bat value) {
        return new JAXBElement<Bat>(_Bat_QNAME, Bat.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BatA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "batA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedMgmtResource")
    public JAXBElement<BatA> createBatA(BatA value) {
        return new JAXBElement<BatA>(_BatA_QNAME, BatA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cmbf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cmbf", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Cmbf> createCmbf(Cmbf value) {
        return new JAXBElement<Cmbf>(_Cmbf_QNAME, Cmbf.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cmdf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cmdf", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Cmdf> createCmdf(Cmdf value) {
        return new JAXBElement<Cmdf>(_Cmdf_QNAME, Cmdf.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cmdv }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cmdv", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Cmdv> createCmdv(Cmdv value) {
        return new JAXBElement<Cmdv>(_Cmdv_QNAME, Cmdv.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cmpv }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cmpv", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Cmpv> createCmpv(Cmpv value) {
        return new JAXBElement<Cmpv>(_Cmpv_QNAME, Cmpv.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cml }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cml", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Cml> createCml(Cml value) {
        return new JAXBElement<Cml>(_Cml_QNAME, Cml.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cmnr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cmnr", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Cmnr> createCmnr(Cmnr value) {
        return new JAXBElement<Cmnr>(_Cmnr_QNAME, Cmnr.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cmwr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cmwr", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Cmwr> createCmwr(Cmwr value) {
        return new JAXBElement<Cmwr>(_Cmwr_QNAME, Cmwr.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cmp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cmp", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Cmp> createCmp(Cmp value) {
        return new JAXBElement<Cmp>(_Cmp_QNAME, Cmp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "mem", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Mem> createMem(Mem value) {
        return new JAXBElement<Mem>(_Mem_QNAME, Mem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MemA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "memA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedMgmtResource")
    public JAXBElement<MemA> createMemA(MemA value) {
        return new JAXBElement<MemA>(_MemA_QNAME, MemA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fwr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "fwr", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Fwr> createFwr(Fwr value) {
        return new JAXBElement<Fwr>(_Fwr_QNAME, Fwr.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FwrA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "fwrA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedMgmtResource")
    public JAXBElement<FwrA> createFwrA(FwrA value) {
        return new JAXBElement<FwrA>(_FwrA_QNAME, FwrA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Swr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "swr", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Swr> createSwr(Swr value) {
        return new JAXBElement<Swr>(_Swr_QNAME, Swr.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SwrA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "swrA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedMgmtResource")
    public JAXBElement<SwrA> createSwrA(SwrA value) {
        return new JAXBElement<SwrA>(_SwrA_QNAME, SwrA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dvi }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "dvi", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Dvi> createDvi(Dvi value) {
        return new JAXBElement<Dvi>(_Dvi_QNAME, Dvi.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DviA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "dviA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedMgmtResource")
    public JAXBElement<DviA> createDviA(DviA value) {
        return new JAXBElement<DviA>(_DviA_QNAME, DviA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dvc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "dvc", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Dvc> createDvc(Dvc value) {
        return new JAXBElement<Dvc>(_Dvc_QNAME, Dvc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DvcA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "dvcA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedMgmtResource")
    public JAXBElement<DvcA> createDvcA(DvcA value) {
        return new JAXBElement<DvcA>(_DvcA_QNAME, DvcA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rbo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "rbo", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Rbo> createRbo(Rbo value) {
        return new JAXBElement<Rbo>(_Rbo_QNAME, Rbo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RboA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "rboA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedMgmtResource")
    public JAXBElement<RboA> createRboA(RboA value) {
        return new JAXBElement<RboA>(_RboA_QNAME, RboA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Evl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "evl", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_mgmtResource")
    public JAXBElement<Evl> createEvl(Evl value) {
        return new JAXBElement<Evl>(_Evl_QNAME, Evl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EvlA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "evlA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedMgmtResource")
    public JAXBElement<EvlA> createEvlA(EvlA value) {
        return new JAXBElement<EvlA>(_EvlA_QNAME, EvlA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Nod }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "nod", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableResource")
    public JAXBElement<Nod> createNod(Nod value) {
        return new JAXBElement<Nod>(_Nod_QNAME, Nod.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "nodA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedResource")
    public JAXBElement<NodA> createNodA(NodA value) {
        return new JAXBElement<NodA>(_NodA_QNAME, NodA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Lcp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "lcp", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableResource")
    public JAXBElement<Lcp> createLcp(Lcp value) {
        return new JAXBElement<Lcp>(_Lcp_QNAME, Lcp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LcpA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "lcpA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedResource")
    public JAXBElement<LcpA> createLcpA(LcpA value) {
        return new JAXBElement<LcpA>(_LcpA_QNAME, LcpA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Csr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "csr", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announceableResource")
    public JAXBElement<Csr> createCsr(Csr value) {
        return new JAXBElement<Csr>(_Csr_QNAME, Csr.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CsrA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "csrA", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedResource")
    public JAXBElement<CsrA> createCsrA(CsrA value) {
        return new JAXBElement<CsrA>(_CsrA_QNAME, CsrA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "exin", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Exin> createExin(Exin value) {
        return new JAXBElement<Exin>(_Exin_QNAME, Exin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mgc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "mgc", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Mgc> createMgc(Mgc value) {
        return new JAXBElement<Mgc>(_Mgc_QNAME, Mgc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Evcg }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "evcg", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Evcg> createEvcg(Evcg value) {
        return new JAXBElement<Evcg>(_Evcg_QNAME, Evcg.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Stcg }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "stcg", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Stcg> createStcg(Stcg value) {
        return new JAXBElement<Stcg>(_Stcg_QNAME, Stcg.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Stcl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "stcl", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Stcl> createStcl(Stcl value) {
        return new JAXBElement<Stcl>(_Stcl_QNAME, Stcl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link org.eclipse.basyx.onem2m.xml.protocols.Req }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "req", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<org.eclipse.basyx.onem2m.xml.protocols.Req> createReq(org.eclipse.basyx.onem2m.xml.protocols.Req value) {
        return new JAXBElement<org.eclipse.basyx.onem2m.xml.protocols.Req>(_Req_QNAME, org.eclipse.basyx.onem2m.xml.protocols.Req.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dlv }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "dlv", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Dlv> createDlv(Dlv value) {
        return new JAXBElement<Dlv>(_Dlv_QNAME, Dlv.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Svsn }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "svsn", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Svsn> createSvsn(Svsn value) {
        return new JAXBElement<Svsn>(_Svsn_QNAME, Svsn.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mssp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "mssp", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Mssp> createMssp(Mssp value) {
        return new JAXBElement<Mssp>(_Mssp_QNAME, Mssp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Asar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "asar", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Asar> createAsar(Asar value) {
        return new JAXBElement<Asar>(_Asar_QNAME, Asar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rol }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "rol", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Rol> createRol(Rol value) {
        return new JAXBElement<Rol>(_Rol_QNAME, Rol.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tk }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "tk", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Tk> createTk(Tk value) {
        return new JAXBElement<Tk>(_Tk_QNAME, Tk.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cb }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "cb", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_resource")
    public JAXBElement<Cb> createCb(Cb value) {
        return new JAXBElement<Cb>(_Cb_QNAME, Cb.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dac }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "dac", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Dac> createDac(Dac value) {
        return new JAXBElement<Dac>(_Dac_QNAME, Dac.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Gio }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "gio", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_flexContainerResource")
    public JAXBElement<Gio> createGio(Gio value) {
        return new JAXBElement<Gio>(_Gio_QNAME, Gio.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Gioa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "gioa", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedFlexContainerResource")
    public JAXBElement<Gioa> createGioa(Gioa value) {
        return new JAXBElement<Gioa>(_Gioa_QNAME, Gioa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Gis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "gis", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_flexContainerResource")
    public JAXBElement<Gis> createGis(Gis value) {
        return new JAXBElement<Gis>(_Gis_QNAME, Gis.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Gisa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "gisa", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedFlexContainerResource")
    public JAXBElement<Gisa> createGisa(Gisa value) {
        return new JAXBElement<Gisa>(_Gisa_QNAME, Gisa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "atrl")
    public JAXBElement<List<String>> createAtrl(List<String> value) {
        return new JAXBElement<List<String>>(_Atrl_QNAME, ((Class) List.class), null, ((List<String> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "rce")
    public JAXBElement<ResourceWrapper> createRce(ResourceWrapper value) {
        return new JAXBElement<ResourceWrapper>(_Rce_QNAME, ResourceWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "uril")
    public JAXBElement<List<String>> createUril(List<String> value) {
        return new JAXBElement<List<String>>(_Uril_QNAME, ((Class) List.class), null, ((List<String> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "uri")
    public JAXBElement<String> createUri(String value) {
        return new JAXBElement<String>(_Uri_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AggregatedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "agr")
    public JAXBElement<AggregatedResponse> createAgr(AggregatedResponse value) {
        return new JAXBElement<AggregatedResponse>(_Agr_QNAME, AggregatedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListOfChildResourceRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "rrl")
    public JAXBElement<ListOfChildResourceRef> createRrl(ListOfChildResourceRef value) {
        return new JAXBElement<ListOfChildResourceRef>(_Rrl_QNAME, ListOfChildResourceRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "dbg")
    public JAXBElement<String> createDbg(String value) {
        return new JAXBElement<String>(_Dbg_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Notification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sgn")
    public JAXBElement<Notification> createSgn(Notification value) {
        return new JAXBElement<Notification>(_Sgn_QNAME, Notification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AggregatedNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "agn")
    public JAXBElement<AggregatedNotification> createAgn(AggregatedNotification value) {
        return new JAXBElement<AggregatedNotification>(_Agn_QNAME, AggregatedNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "seci")
    public JAXBElement<SecurityInfo> createSeci(SecurityInfo value) {
        return new JAXBElement<SecurityInfo>(_Seci_QNAME, SecurityInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pdr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "pdr", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Pdr> createPdr(Pdr value) {
        return new JAXBElement<Pdr>(_Pdr_QNAME, Pdr.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ntp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ntp", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_regularResource")
    public JAXBElement<Ntp> createNtp(Ntp value) {
        return new JAXBElement<Ntp>(_Ntp_QNAME, Ntp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajfw }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajfw", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_flexContainerResource")
    public JAXBElement<Ajfw> createAjfw(Ajfw value) {
        return new JAXBElement<Ajfw>(_Ajfw_QNAME, Ajfw.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajfwa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajfwa", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedFlexContainerResource")
    public JAXBElement<Ajfwa> createAjfwa(Ajfwa value) {
        return new JAXBElement<Ajfwa>(_Ajfwa_QNAME, Ajfwa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajsw }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajsw", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_flexContainerResource")
    public JAXBElement<Ajsw> createAjsw(Ajsw value) {
        return new JAXBElement<Ajsw>(_Ajsw_QNAME, Ajsw.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ajswa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "ajswa", substitutionHeadNamespace = "http://www.onem2m.org/xml/protocols", substitutionHeadName = "sg_announcedFlexContainerResource")
    public JAXBElement<Ajswa> createAjswa(Ajswa value) {
        return new JAXBElement<Ajswa>(_Ajswa_QNAME, Ajswa.class, null, value);
    }

}
