//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announcedResource"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dcrp" type="{http://www.onem2m.org/xml/protocols}descriptorRepresentation" minOccurs="0"/&gt;
 *         &lt;element name="soe" type="{http://www.onem2m.org/xml/protocols}sparql" minOccurs="0"/&gt;
 *         &lt;element name="dsp" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="or" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *         &lt;element name="rels" type="{http://www.onem2m.org/xml/protocols}listOfURIs" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}sub" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dcrp",
    "soe",
    "dsp",
    "or",
    "rels",
    "ch",
    "sub"
})
public class SmdA
    extends AnnouncedResource
{

    protected String dcrp;
    protected String soe;
    protected byte[] dsp;
    @XmlSchemaType(name = "anyURI")
    protected String or;
    @XmlList
    protected List<String> rels;
    protected List<ChildResourceRef> ch;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Sub> sub;

    /**
     * Gets the value of the dcrp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDcrp() {
        return dcrp;
    }

    /**
     * Sets the value of the dcrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDcrp(String value) {
        this.dcrp = value;
    }

    /**
     * Gets the value of the soe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoe() {
        return soe;
    }

    /**
     * Sets the value of the soe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoe(String value) {
        this.soe = value;
    }

    /**
     * Gets the value of the dsp property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDsp() {
        return dsp;
    }

    /**
     * Sets the value of the dsp property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDsp(byte[] value) {
        this.dsp = value;
    }

    /**
     * Gets the value of the or property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOr() {
        return or;
    }

    /**
     * Sets the value of the or property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOr(String value) {
        this.or = value;
    }

    /**
     * Gets the value of the rels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRels() {
        if (rels == null) {
            rels = new ArrayList<String>();
        }
        return this.rels;
    }

    /**
     * Gets the value of the ch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getCh() {
        if (ch == null) {
            ch = new ArrayList<ChildResourceRef>();
        }
        return this.ch;
    }

    /**
     * Gets the value of the sub property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sub property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSub().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sub }
     * 
     * 
     */
    public List<Sub> getSub() {
        if (sub == null) {
            sub = new ArrayList<Sub>();
        }
        return this.sub;
    }

}
