//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 09:48:33 AM CET 
//


package org.eclipse.basyx.onem2m.xml.protocols;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announceableSubordinateResource"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dgt" type="{http://www.onem2m.org/xml/protocols}absRelTimestamp"/&gt;
 *         &lt;element name="con" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/&gt;
 *         &lt;element name="snr" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dgt",
    "con",
    "snr"
})
public class Tsi
    extends AnnounceableSubordinateResource
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String dgt;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected Object con;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger snr;

    /**
     * Gets the value of the dgt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDgt() {
        return dgt;
    }

    /**
     * Sets the value of the dgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDgt(String value) {
        this.dgt = value;
    }

    /**
     * Gets the value of the con property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCon() {
        return con;
    }

    /**
     * Sets the value of the con property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCon(Object value) {
        this.con = value;
    }

    /**
     * Gets the value of the snr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSnr() {
        return snr;
    }

    /**
     * Sets the value of the snr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSnr(BigInteger value) {
        this.snr = value;
    }

}
