version: '3'
services:

  registry:
    image: eclipsebasyx/aas-registry:1.0.1
    container_name: dashboard-registry
    ports:
      - 4000:4000

  dashboard-aas:
    image: eclipsebasyx/dashboard-aas:0.1.0-SNAPSHOT
    container_name: dashboard-aas
    environment:
      - BaSyxDashboardSubmodel_Min=15
#      - BaSyxDashboardSubmodel_Max=30
    ports:
      - 6400:6400

  aas-wrapper:
    image: eclipsebasyx/aas-wrapper:0.1.0-SNAPSHOT
    container_name: aas-wrapper
    ports:
      - 6500:6500

  node-red:
    image: eclipsebasyx/examples-dataflow-nodered:0.1.0-SNAPSHOT
    container_name: node-red
    ports:
      - 1880:1880
    volumes:
      - ./node-red:/data

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log